# SQLite. Versions 3.8.0 and up are supported.
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem "sqlite3"
#
default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root
  password: Adsf4231!
  host: db

development:
  <<: *default
  database: railstutorial_development
test:
  <<: *default
  database: railstutorial_test
production:
  <<: *default
  adapter: mysql2
  encoding: utf8mb4
  database: railstutorial_production
  username: root
  password: Adsf4231!
